import * as LucideIcons from 'lucide-react';

const serviceIcons = {
  'Formatação ABNT Básica': LucideIcons.AlignLeft,
  'Formatação ABNT Avançada': LucideIcons.AlignLeft,
  'Revisão Ortográfica': LucideIcons.Type,
  'Revisão Ortográfica e Gramatical': LucideIcons.Type,
  'Revisão Completa com Adequação Acadêmica': LucideIcons.CheckCircle,
  'TCC Parcial': LucideIcons.GraduationCap,
  'TCC Completo': LucideIcons.GraduationCap,
  'Artigo Científico': LucideIcons.Award,
  'Projeto de Pesquisa': LucideIcons.Search,
  'Relatórios': LucideIcons.BarChart3,
  'Pesquisa Acadêmica': LucideIcons.Microscope,
  'Redação Acadêmica': LucideIcons.PenTool,
  'Referências Bibliográficas': LucideIcons.BookMarked,

  'Currículo Básico': LucideIcons.FileText,
  'Currículo Profissional': LucideIcons.FileText,
  'Currículo Executivo': LucideIcons.FileText,
  'Revisão de Currículo': LucideIcons.RefreshCw,
  'Carta de Apresentação': LucideIcons.Send,
  'Perfil para LinkedIn': LucideIcons.UserCheck,
  'Cadastro em Vagas de Emprego': LucideIcons.Briefcase,

  'Gov.br': LucideIcons.ShieldCheck,
  'Certidões': LucideIcons.FileCheck,
  'Emissão de Certidão Negativa de Débitos': LucideIcons.FileCheck,
  'Antecedentes Criminais': LucideIcons.ShieldAlert,
  'BO – Boletim de Ocorrência Policial': LucideIcons.FileText,
  'Declarações em Geral': LucideIcons.FileOutput,
  'Declaração de Isenção do Imposto de Renda': LucideIcons.FileCheck,
  'Emissão de DAS MEI': LucideIcons.Receipt,
  'Emissão de DAE/DAJ/DAE-MI': LucideIcons.Receipt,
  'Consultas de Débitos e Pendências Online': LucideIcons.Search,
  'Consultas ao DETRAN': LucideIcons.Car,
  'CRLV-E': LucideIcons.FileCheck,
  'Segunda Via de Contas/Boletos': LucideIcons.FileWarning,
  '2ª Via de Documentos via Internet': LucideIcons.FileOutput,
  'Inscrição em Concursos': LucideIcons.ClipboardCheck,
  'Inscrição em Vestibulares': LucideIcons.GraduationCap,

  'Digitação em Geral': LucideIcons.Keyboard,
  'Procurações e Autorizações': LucideIcons.FileSignature,
  'Redação de Contratos Diversos': LucideIcons.FileText,
  'Revisão de Contratos': LucideIcons.CheckCircle,

  'Impressão Preto e Branco': LucideIcons.Printer,
  'Impressão Colorida': LucideIcons.Printer,
  'Xerox Preto e Branco': LucideIcons.Copy,
  'Xerox Colorida': LucideIcons.Copy,
  'Scanner para PDF (até 20 páginas)': LucideIcons.ScanLine,
  'Scanner para PDF (acima de 20 páginas)': LucideIcons.ScanLine,
  'Conversão PDF para Word': LucideIcons.FileDown,
  'Conversão Word para PDF': LucideIcons.FileUp,
  'Conversão de Arquivos': LucideIcons.RefreshCw,
  'Encadernação': LucideIcons.BookOpen,
  'Plastificação': LucideIcons.Shield,

  'Cadastro Google Meu Negócio': LucideIcons.MapPin,
  'Otimização Google Meu Negócio': LucideIcons.MapPin,
  'WhatsApp Business Configuração Básica': LucideIcons.MessageCircle,
  'WhatsApp Business Configuração Completa com Catálogo': LucideIcons.MessageCircle,
  'Instagram Comercial Configuração Básica': LucideIcons.Camera,
  'Instagram Comercial Configuração Completa': LucideIcons.Camera,
  'Link de Bio Simples': LucideIcons.Link,
  'Link de Bio Personalizado': LucideIcons.Link,
  'QR Code Simples': LucideIcons.QrCode,
  'QR Code Personalizado': LucideIcons.QrCode,

  'Identidade Visual Básica': LucideIcons.Palette,
  'Identidade Visual Intermediária': LucideIcons.Palette,
  'Identidade Visual Completa': LucideIcons.Palette,
  'Logo Básico': LucideIcons.Diamond,
  'Logo Profissional': LucideIcons.Diamond,
  'Logo Premium': LucideIcons.Diamond,
  'Cardápio Digital Básico': LucideIcons.BookOpen,
  'Cardápio Digital Profissional': LucideIcons.BookOpen,
  'Cardápio Impresso': LucideIcons.BookOpen,
  'Catálogo Digital até 20 Produtos': LucideIcons.Library,
  'Catálogo Digital até 50 Produtos': LucideIcons.Library,
  'Catálogo Digital acima de 50 Produtos': LucideIcons.Library,
  'Cartões de Visita': LucideIcons.CreditCard,
  'Panfletos': LucideIcons.FileSpreadsheet,
  'Materiais Promocionais': LucideIcons.Megaphone,
  'Arte Avulsa': LucideIcons.Paintbrush,
  'Pacote com 5 Artes': LucideIcons.Paintbrush,
  'Pacote com 10 Artes': LucideIcons.Paintbrush,
  'Posts para Redes Sociais': LucideIcons.Image,
  'Stories para Redes Sociais': LucideIcons.Play,
  'Criação de Legendas': LucideIcons.Quote,
  'Conteúdo para Redes Sociais': LucideIcons.MessageSquare,

  'Landing Page Básica': LucideIcons.Layout,
  'Landing Page Profissional': LucideIcons.Layout,
  'Landing Page com Integrações': LucideIcons.Layout,
  'Site One Page': LucideIcons.Globe,
  'Site até 5 Páginas': LucideIcons.Globe,
  'Site até 10 Páginas': LucideIcons.Globe,
  'Formulário Simples': LucideIcons.FileInput,
  'Formulário Avançado': LucideIcons.FileInput,
  'Sistema Web Simples': LucideIcons.Monitor,
  'Sistema Web Sob Medida': LucideIcons.Code,

  'Formatação Simples de Computador': LucideIcons.Monitor,
  'Formatação com Backup': LucideIcons.Monitor,
  'Instalação de Programas': LucideIcons.Download,
  'Pacote de Programas': LucideIcons.Download,
  'Backup Simples': LucideIcons.HardDrive,
  'Backup Completo': LucideIcons.HardDrive,
  'Configuração de Impressora Básica': LucideIcons.Printer,
  'Configuração de Impressora em Rede': LucideIcons.Printer,
  'Organização Digital Simples': LucideIcons.FolderOpen,
  'Organização Digital Completa': LucideIcons.FolderOpen,
  'Downloads': LucideIcons.Download,
  'Envios de E-mail': LucideIcons.Mail,
  'Suporte Remoto': LucideIcons.Wifi,
  'Suporte Presencial': LucideIcons.Headphones,
  'Solução de Dúvidas Rápidas': LucideIcons.HelpCircle,

  'Etiquetas Simples': LucideIcons.Tag,
  'Etiquetas Personalizadas Premium': LucideIcons.Tag,
  'Tags até 50 Unidades': LucideIcons.Tag,
  'Tags até 100 Unidades': LucideIcons.Tag,
  'Tags acima de 100 Unidades': LucideIcons.Tag,
  'Cartões de Agradecimento Modelo Simples': LucideIcons.Heart,
  'Cartões de Agradecimento Modelo Personalizado': LucideIcons.Heart,
  'Adesivos para Embalagens Folha A4': LucideIcons.Package,
  'Adesivos para Embalagens Folha A3': LucideIcons.Package,
  'Tabela de Preços Digital': LucideIcons.Table,
  'Tabela de Preços Impressa': LucideIcons.Table,
  'QR Code Empresarial Simples': LucideIcons.QrCode,
  'QR Code Empresarial Personalizado': LucideIcons.QrCode,
  'Artes para Divulgação Avulsa': LucideIcons.Megaphone,
  'Pacote com 5 Artes para Divulgação': LucideIcons.Megaphone,
  'Pacote com 10 Artes para Divulgação': LucideIcons.Megaphone,
  'Kit Inicial para Pequenos Negócios': LucideIcons.Package,
  'Kit Profissional para Pequenos Negócios': LucideIcons.Package,
  'Kit Premium para Pequenos Negócios': LucideIcons.Package,
  'Reposição Mensal de Materiais (Plano Básico)': LucideIcons.RefreshCw,
  'Reposição Mensal de Materiais (Plano Intermediário)': LucideIcons.RefreshCw,
  'Reposição Mensal de Materiais (Plano Completo)': LucideIcons.RefreshCw,

  'Convite Digital e Impresso': LucideIcons.Mail,
  'Tag para Lembrancinha': LucideIcons.Gift,
  'Rótulo Personalizado': LucideIcons.Tag,
  'Plaquinha Decorativa': LucideIcons.PanelTop,
  'Mini Kit de Festa': LucideIcons.Gift,
  'Item Personalizado para Mesa': LucideIcons.Coffee,
  'Kit Impresso para Festa': LucideIcons.Package,

  'Calculadora de Orçamento': LucideIcons.Calculator,
  'Geração de PDF de Orçamento': LucideIcons.FileText,
  'Geração de Etiquetas e Tags': LucideIcons.Tag,
  'Controle de Estoque': LucideIcons.Box,
  'Validação de QR Codes': LucideIcons.ScanLine,
  'Cadastro e Gestão de Pedidos': LucideIcons.ClipboardList,
  'Página Digital para Negócio': LucideIcons.Monitor,

  'Botton 32mm': LucideIcons.Circle,
  'Botton 37mm': LucideIcons.Circle,
  'Botton 44mm': LucideIcons.Circle,
  'Botton 58mm': LucideIcons.Circle,
  'Botton Chaveiro': LucideIcons.Key,
  'Botton Ímã de Geladeira': LucideIcons.Circle,
  'Criação de Arte para Botton': LucideIcons.Paintbrush,
  'Arte Adicional por Variação de Layout': LucideIcons.Paintbrush
};

const fallbackIcons = {
  'trabalhos-academicos': LucideIcons.BookOpen,
  'curriculos-carreira': LucideIcons.FileText,
  'servicos-online-burocraticos': LucideIcons.FileCheck,
  'redacao-digitação-contratos': LucideIcons.PenLine,
  'impressao-digitalizacao': LucideIcons.Printer,
  'presenca-digital': LucideIcons.Smartphone,
  'comerciantes-autonomos': LucideIcons.Store,
  'desenvolvimento-web': LucideIcons.Globe,
  'informatica-suporte': LucideIcons.Wrench,
  'personalizacao-impressa': LucideIcons.Tag,
  'festas-personalizados': LucideIcons.PartyPopper,
  'automacao-solucoes-digitais': LucideIcons.Bot,
  'bottons-personalizados': LucideIcons.Circle
};

export function getServiceIcon(serviceName) {
  return serviceIcons[serviceName] || LucideIcons.HelpCircle;
}

export function getCategoryIcon(categoryId) {
  return fallbackIcons[categoryId] || LucideIcons.HelpCircle;
}
